name: brawl
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Nico Hämäläinen <nico@sizeof.io>
homepage: http://sizeof.io

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  events: ">=0.0.0 <2.0.0"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
